general {
    hide_cursor = true
    grace = 0
}

background {
    monitor =
    color = rgb(1d2021)
}

input-field {
    monitor =
    size = 200, 24
    position = 0, -60
    halign = center
    valign = center

    outline_thickness = 1
    outer_color = rgb(3c3836)
    inner_color = rgb(282828)
    font_color  = rgb(ebdbb2)
    check_color = rgb(d79921)
    fail_color  = rgb(cc241d)

    font_family = Hack
    font_size = 10

    placeholder_text =
    fail_text = $FAIL ($ATTEMPTS)
    hide_input = false
    rounding = 0

    dots_size = 0.2
    dots_spacing = 0.3
}

label {
    monitor =
    text = $TIME
    position = 0, 80
    halign = center
    valign = center

    font_family = Hack
    font_size = 48
    color = rgb(ebdbb2)
}

label {
    monitor =
    text = $LAYOUT[en,]
    position = 0, -100
    halign = center
    valign = center

    font_family = Hack
    font_size = 10
    color = rgb(928374)
}
